CREATE TABLE IF NOT EXISTS news
(
    id    BIGSERIAL NOT NULL PRIMARY KEY ,
    title  VARCHAR(200) NOT NULL ,
    text VARCHAR(3000) NOT NULL ,
    DATE DATE  NOT NULL
);
-- DROP TABLE IF EXISTS news